#!/bin/bash

set -e # exit on error
set -x # echo commands

# install NPM dependencies
pushd bokehjs
npm install
popd

# download the previous BokehJS build directory to run tests
pushd ${HOME}
wget -nv "https://s3.amazonaws.com/bokeh-travis/${TRAVIS_BUILD_ID}/bokehjs-build.tgz"
tar xzf bokehjs-build.tgz
popd

py.test -s -m js
