#!/bin/bash

set -e # exit on error
set -x # echo commands

if [[ $TRAVIS_COMMIT_MSG == *"[ci disable examples]"* ]]; then
    echo
    echo " SKIPPING EXAMPLES TESTS --- disabled by commit message"
    echo
    exit 0
fi

# install NPM dependencies and build JS examples
pushd bokehjs
npm install
node_modules/.bin/gulp examples --no-build
popd

# download the previous BokehJS build directory to run tests
pushd ${HOME}
wget -nv "https://s3.amazonaws.com/bokeh-travis/${TRAVIS_BUILD_ID}/bokehjs-build.tgz"
tar xzf bokehjs-build.tgz
popd

# install Bokeh sample data needed by examples
python -c 'import bokeh; bokeh.sampledata.download(progress=False)'

py.test -s -v -m examples       \
    --tb line                   \
    --diff-ref FETCH_HEAD       \
    --self-contained-html       \
    --upload                    \
    --report-path=examples.html \
    ${EXTRA_CMD}
